spring.application.name=Job-Application-Tracker 
server.port=3212

spring.datasource.url=jdbc:mysql://localhost:3306/job_app
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsAJWTSecretrandom-256-bit-string-so-it-cant-be-guessed
jwt.expiration=86400000

